[PWD-2475] Corporate Training Page
PurwadhikaDev/purwadhika-corporate-website pull request #19
Opened 2023-07-18 10:17 UTC by gangsararyop

### What type of PR is this? (_check all applicable_)

- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update
- [ ] Setup
- [ ] Code Refactor
- [ ] Performance Improvements
- [ ] Test
- [ ] Build
- [ ] CI
- [ ] Revert

### Screenshots (_optional_)

![image](https://github.com/PurwadhikaDev/purwadhika-corporate-website/assets/86463063/962e58ee-7bab-4a7c-9fa6-39f3087f881f)

2023-07-20 01:49 UTC, shadiqfauzi commented on src/components/ProgramCard.tsx
> +  strapi?: boolean
```suggestion
  isStrapiImage?: boolean
```

2023-07-20 01:50 UTC, shadiqfauzi commented on src/features/corporate-training/api/useGetProgramOptions.ts
> +    ['program-categories', title],
```suggestion
    ['strapi-program-categories', title],
```
buat data yang dari strapi kayanya harus di tambah keynya kaya gini, soalnya takutnya bentrok keynya sama yang dari api

2023-07-20 06:40 UTC, shadiqfauzi commented on src/features/program/api/useGetStrapiProgramOptions.ts
> +    ['program-categories', title],
```suggestion
    ['strapi-program-categories', title],
```
buat yang get dari strapi keynya kaya gini aja biar kalau ada yang get dari BE purwadhika ga bentrok key nya

2023-07-20 06:41 UTC, shadiqfauzi commented on src/views/corporate-training/types.ts
> +  selectedLanguage: string
harusnya sih disini bisa di define kita punya topic, method apa aja, jadi ga generic string

2023-07-20 06:46 UTC, gangsararyop commented on src/views/corporate-training/types.ts
> +  selectedLanguage: string
enum yak?

2023-07-20 06:52 UTC, shadiqfauzi commented on src/views/corporate-training/types.ts
> +  selectedLanguage: string
betul

2023-07-21 02:37 UTC, shadiqfauzi requested changes
nanti rerequest lg yak kalau udah kelar, biar ga padet pr review request w wkwk

2023-07-24 03:01 UTC, hiljaker commented on src/components/PWDKSelect.tsx
> +}: SelectProps) => (
```suggestion
const SelectComponent: FC<SelectProps> = ({
  filled,
  size,
  label,
  error,
  ...props
}) => (
```

2023-07-24 03:09 UTC, hiljaker commented on src/views/corporate-training/components/ProgramCards.tsx
> +}) => {
```suggestion
interface ProgramCardsProps {
    state: State
    selectedTab: Tab
}

const ProgramCards: FC<ProgramCardsProps> = ({
  state,
  selectedTab
}) => {
```

2023-07-24 03:10 UTC, hiljaker commented on src/views/corporate-training/components/ProgramFilter.tsx
> +const ProgramFilter: FC<{
belah sini juga nih masz

2023-07-24 03:10 UTC, gangsararyop commented on src/views/corporate-training/components/ProgramFilter.tsx
> +const ProgramFilter: FC<{
siyapp

2023-07-24 03:18 UTC, hiljaker submitted a review, later dismissed
𝓛esgooo 𝓜asgang

2023-07-24 07:27 UTC, Vesals submitted a review, later dismissed

2023-07-25 02:18 UTC, shadiqfauzi commented on src/features/program/types/strapiProgram.ts
> +  programCategory: string
```suggestion
  method?: string
  branch?: string
  language?: string
  category?: string
  programCategory: string
```
ini bukannya bisa dipake enum jg ya kaya di program options? ambil yang dari program options aja sama kan ya

2023-07-25 02:36 UTC, gangsararyop commented on src/features/program/types/strapiProgram.ts
> +  programCategory: string
iyaa deng, gw adjust dlu

2023-07-26 08:19 UTC, shadiqfauzi approved these changes

2023-07-27 02:18 UTC, Vesals approved these changes

2023-07-27 03:14 UTC, merged