[PWD-2471] Learning Material Watch Page
PurwadhikaDev/purwadhika-corporate-website pull request #21
Opened 2023-07-20 02:53 UTC by FahemHakikiKhaya

### What type of PR is this? (_check all applicable_)

- [ ] Feature
- [ ] Bug Fix
- [ ] Documentation Update
- [ ] Setup
- [ ] Code Refactor
- [ ] Performance Improvements
- [ ] Test
- [ ] Build
- [ ] CI
- [ ] Revert

### Screenshots (_optional_)

2023-07-20 09:43 UTC, ansorudin commented on src/features/online-course/types/OnlineCourse.ts
> +  OnlineCourseUserProgress: CourseProgress
```suggestion
  onlineCourseUserProgress: CourseProgress
```

2023-07-21 02:25 UTC, shadiqfauzi commented on src/features/online-course/types/OnlineCourse.ts
> +  OnlineCourseUserProgress: CourseProgress
feeling gue ini response data dari BE, dosa lama yang kalau mau diampuni harus adjust banyak code wkwkw

2023-07-21 02:37 UTC, shadiqfauzi requested changes
nanti rerequest lg yak kalau udah kelar, biar ga padet pr review request w wkwk

2023-07-21 07:24 UTC, hiljaker commented on src/features/watch-history/api/useCreateWatchHisotry.ts
typo nih nama filenya

2023-07-21 07:26 UTC, FahemHakikiKhaya commented on src/features/watch-history/api/useCreateWatchHisotry.ts
itu pake accent jepang gw zak

2023-07-21 07:34 UTC, hiljaker commented on src/features/online-course/api/usetGetOnlineCourseDetail.ts
> +    const onlineCourse = await api<{ data: OnlineCourse }>(
bisa nih dibuatin type atau interface mungkin OnlineCourseDetailResponse?

2023-07-21 07:37 UTC, hiljaker commented on src/views/watch/components/Menulist/components/Menuitem.tsx
> +  // const isCompleted = progressLookup?.find(
𝒜𝓭𝒶 𝒞𝓸mment

2023-07-21 07:39 UTC, hiljaker commented on src/features/watch-history/api/useCreateWatchHisotry.ts
hisutori gozaimasu

2023-07-26 08:17 UTC, shadiqfauzi commented
masih on progres gak nich

2023-07-26 08:38 UTC, FahemHakikiKhaya commented
> masih on progres gak nich

udh

2023-07-27 02:30 UTC, shadiqfauzi commented on src/features/online-course/api/useGetOnlineCourseTopics.ts
nitip disini keynya masih `'topics'`, mungkin bisa diganti jadi `online-course-topics`

2023-07-27 02:31 UTC, shadiqfauzi commented on src/features/watch-history/api/useCreateWatchHistory.ts
> +interface CreateWathHistoryParams {
```suggestion
interface CreateWatchHistoryParams {
```

2023-07-27 02:33 UTC, shadiqfauzi commented on src/features/online-course/types/ProgramProps.ts
ini kalau di db type buat apa ya? kalau emang program tp khusus buat online course mungkin bisa di rename jadi `OnlineCourseProgramProps`

2023-07-27 03:26 UTC, FahemHakikiKhaya commented on src/features/online-course/types/ProgramProps.ts
ini kebutuhan @hiljaker

2023-07-31 07:44 UTC, Vesals commented on src/views/watch/components/Videoplayer/components/VideoScreen.tsx
> +        height: { xs: '210px', sm: '360px', md: '400px', lg: '550px' },
buang ni xs sama sm-nya ga akan kepake

2023-08-01 02:03 UTC, Vesals commented on src/views/watch/components/Menulist/components/Collapsible.tsx
> +            key={item.title}
toArray

2023-08-01 02:03 UTC, Vesals commented on src/views/watch/components/Menulist/components/Collapsible.tsx
> +            key={item.title}
toArray

2023-08-01 03:03 UTC, hiljaker commented on src/views/watch/components/Menulist/components/Menuitem.tsx
> +        borderLeft: selected && `4px solid ${theme.palette.success.main}`
warning nih pasti
```suggestion
        borderLeft: selected ? `4px solid ${theme.palette.success.main}` : undefined
```

2023-08-01 03:07 UTC, hiljaker commented on src/views/watch/components/Menulist/index.tsx
> +  return menu?.map((item, index) => {
Children.toArray

2023-08-01 03:35 UTC, Vesals commented on src/views/watch/components/Menulist/index.tsx
> +const MenuList = ({
```suggestion
const MenuList: FC<MenuListProps> = ({
```

2023-08-01 03:36 UTC, Vesals commented on src/views/watch/components/Menulist/index.tsx
> +}: MenuListProps) => {
```suggestion
}) => {
```

2023-08-01 03:38 UTC, FahemHakikiKhaya commented on src/views/watch/components/Menulist/components/Menuitem.tsx
> +        borderLeft: selected && `4px solid ${theme.palette.success.main}`
ASIAP BANG MESSI

2023-08-01 06:13 UTC, kuntiarso approved these changes

2023-08-01 06:25 UTC, Vesals approved these changes

2023-08-01 07:06 UTC, shadiqfauzi approved these changes

2023-08-01 07:13 UTC, merged